## Goal --> Maximize the minimum distance of point from the hyperplane.
##      --> meaning that the points closest to the HP , must be well separated.

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

In [2]:
data = np.load('dataset/mnist_train_small.npy')

In [3]:
data

array([[5, 0, 0, ..., 0, 0, 0],
       [7, 0, 0, ..., 0, 0, 0],
       [9, 0, 0, ..., 0, 0, 0],
       ...,
       [2, 0, 0, ..., 0, 0, 0],
       [9, 0, 0, ..., 0, 0, 0],
       [5, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [4]:
X = data[: , 1:]
y = data[: ,0]

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

## Model

In [6]:
from sklearn.svm import SVC
model = SVC()
model.fit(X_train , y_train)

SVC()

In [7]:
y_predict = model.predict(X_test)

In [8]:
y_predict[:15]

array([7, 7, 0, 9, 4, 5, 4, 6, 9, 2, 0, 6, 1, 9, 9], dtype=uint8)

In [9]:
y_test[:15]

array([7, 7, 0, 9, 4, 5, 4, 6, 9, 2, 0, 6, 1, 9, 9], dtype=uint8)

## In Linear Regression model, the first number predicted was '1' instead of '7'. But ,SVM predicts the number correctly as '7'.
## Hence it is better than Linear Regression Model

In [10]:
model.score(X_test , y_test)

0.963939393939394