## Importing Libraries & getting Data

In [1]:
import pandas as pd 
import numpy as np 

In [2]:
data = pd.read_csv("dataset/Salary_Data.csv")
data.head()

YearsExperience   Salary
0              1.1  39343.0
1              1.3  46205.0
2              1.5  37731.0
3              2.0  43525.0
4              2.2  39891.0

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 2 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   YearsExperience  30 non-null     float64
 1   Salary           30 non-null     float64
dtypes: float64(2)
memory usage: 608.0 bytes


## Selecting Features

In [4]:
X = data.iloc[:,:-1].values 
y = data.iloc[:,1].values

X.shape ,y.shape

((30, 1), (30,))

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

X_train.shape ,X_test.shape, y_train.shape ,y_test.shape

((20, 1), (10, 1), (20,), (10,))

## Model

In [6]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train , y_train)

LinearRegression()

In [7]:
model.predict(X_test[:10])

array([115814.30756236,  71511.92534771, 102617.85328566,  75282.34085534,
        55487.65944028,  60200.67882482, 122412.53470072, 107330.8726702 ,
        63028.49045554,  35692.97802523])

In [8]:
y_test[:10]

array([112635.,  67938., 113812.,  83088.,  64445.,  57189., 122391.,
       109431.,  56957.,  39343.])

In [9]:
X_test[:10]

array([[ 9.6],
       [ 4.9],
       [ 8.2],
       [ 5.3],
       [ 3.2],
       [ 3.7],
       [10.3],
       [ 8.7],
       [ 4. ],
       [ 1.1]])

In [10]:
model.score(X_test , y_test)

0.9553063138044949

In [11]:
years = int(input("How many years of experience you have ?"))
salary = model.predict(np.array([years]).reshape(-1,1))

print("Estimated salary for {} years of experience --> ${}".format(years,round(salary[0], 3)))


Estimated salary for 15 years of experience --> $166714.917


In [12]:
# array needs to be 2d because X can have more than 1 features. 
